sudo: required
services:
  - docker

before_install:
   - docker build -t himanshu5692/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true himanshu5692/react-test npm test -- --coverage

after_success:
  - docker build -t himanshu5692/multi-client ./client
  - docker build -t himanshu5692/multi-nginx ./nginx
  - docker build -t himanshu5692/multi-server ./server
  - docker build -t himanshu5692/multi-worker ./worker
  # Login to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take images and push to Docker Hub
  - docker push himanshu5692/multi-client
  - docker push himanshu5692/multi-nginx
  - docker push himanshu5692/multi-server
  - docker push himanshu5692/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-647395822419"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
